### ISSUE TITLE
Store used letters in hangman-cli

### ISSUE THREAD

**Issue by anantdark** [anantdark/hangman#15]
Hangman-GUI removes the letters guessed from the screen, but you can input the same letter multiple times in `hangman-cli`.
The user should get a prompt reminding he has already used this letter and should choose a different one.

**Comment by anantdark** [comment]
The logic for `lives` is good, if using an already used letter, the `lives` remain the same. But the user should still get a prompt.

**Comment by kirkland-signature** [comment]
Hi, please assign me this issue, I might be able to implement this!

**Comment by anantdark** [comment]
Go ahead @kirkland-signature
