### ISSUE TITLE
Ask to play multiple times and keep score for the time.

### ISSUE THREAD

**Issue by anantdark** [anantdark/hangman#16]
Both GUI and CLI implementations exit after running once, the games should give the option to continue and also maintain a scoreboard at the end.

**Comment by RachitGarg-12** [comment]
please assign me this issue

**Comment by anantdark** [comment]
Go ahead @RachitGarg-12 , Let me know if you don't understand anything in the project.

**Comment by anantdark** [comment]
Progress? @RachitGarg-12

**Comment by anantdark** [comment]
Issue is free to be picked by anyone else.
