### ISSUE TITLE
Merge gui and cli

### ISSUE THREAD

**Issue by anantdark** [anantdark/hangman#20]
Currently if the user has to run the game in GUI/CLI mode, he has to run the respective python file in the folder.
Create a "master" python program which after running gives the option to select from GUI/CLI Interface.
The respective python code(GUI/CLI) shall be executed as per the selected option.

- Try not to shift the existing file structure.
- Try not to rename the existing files.

**Comment by yogesh-9999** [comment]
hey @anantdark assign me this issue

**Comment by anantdark** [comment]
Hi @yogesh-9999 , I have assigned it to you, waiting for PR.
However do note that this doesn't give you exclusive access to this issue and any other PR(if submitted) will be reviewed.

**Comment by anantdark** [comment]
@yogesh-9999 progress?
