### ISSUE TITLE
Improve wordlist

### ISSUE THREAD

**Issue by anantdark** [anantdark/hangman#21]
Improve the existing wordlist with better/more-known words, as some of the words in the existing wordlist can't be used in the game because they are too hard to guess.

**Comment by kirkland-signature** [comment]
Hi there! I'd like to work on this issue.

**Comment by jsvigneshkanna** [comment]
I would add some more words

**Comment by anantdark** [comment]
Hello, @kirkland-signature, @jsvigneshkanna start working and send a PR my way.
