### ISSUE TITLE
Show the word's meaning

### ISSUE THREAD

**Issue by anantdark** [anantdark/hangman#22]
After the game has ended, either in lose or win. The user should get the meaning of the word alongside the word.
We can implement it in two ways.
- Change the wordlist to store words and their meanings and show them accordingly.
- Change the code and let the user add the meaning of the word after the game, eventually the wordlist will be full with word meanings.

**Comment by leinadsened** [comment]
We could solve this issue with WordNet, displaying a dictionary definition for the word. Displaying synonyms for the word could also be added with it.

**Comment by anantdark** [comment]
Can you work on it?

**Comment by leinadsened** [comment]
Sure, I'll get started with it
